"use client";
import * as React from "react";
import { Loader2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { reportEntityTypeLabels, reportSeverityLabels, reportStatusLabels, type ReportItem } from "./reports-management.types";
import { getSeverityBadgeClass, getStatusBadgeClass, toDisplayName } from "./helpers";
import { formatUtcDateTime } from "@/lib/date";
import { useAdminReportDetail } from "@/features/admin/reports.services/admin.reports.query";
import { CloseReportDialog } from "./close-report-dialog";
const text=(v:unknown)=>typeof v==='string'||typeof v==='number'?String(v):'-';
function Entity({r}:{r:ReportItem}){const e=r.entity,d=e?.data??{},imgs=Array.isArray(d.images)?d.images.filter((v):v is string=>typeof v==='string'):[];return e?<div className="space-y-2 text-xs">{d.title?<p>العنوان: <b>{text(d.title)}</b></p>:null}{d.name?<p>الاسم: <b>{text(d.name)}</b></p>:null}{d.authorName?<p>صاحب المنشور: <b>{text(d.authorName)}</b></p>:null}{d.organizationName?<p>المنظمة: <b>{text(d.organizationName)}</b></p>:null}{d.summary?<p className="leading-6">{text(d.summary)}</p>:null}{d.content||d.description||d.body?<p className="whitespace-pre-wrap leading-6">{text(d.content??d.description??d.body)}</p>:null}{imgs.length?<div className="grid grid-cols-2 gap-2">{imgs.map(src=><a key={src} href={src} target="_blank" rel="noreferrer"><img src={src} alt="المحتوى المبلغ عنه" className="h-32 w-full rounded-md border object-cover"/></a>)}</div>:null}</div>:<p className="text-xs text-muted-foreground">المحتوى غير متاح.</p>}
type Props={report:ReportItem|null;open:boolean;onOpenChange:(v:boolean)=>void;onClaim:(id:string)=>void;onCloseReport:(id:string,note:string)=>Promise<void>;isClaiming:boolean;claimingReportId?:string;isClosing:boolean;closingReportId?:string};
export function ReportDetailsSheet(p:Props){const [close,setClose]=React.useState(false);const q=useAdminReportDetail(p.open?p.report?.id??null:null);const r=q.data?.data??p.report;if(!r)return <Sheet open={p.open} onOpenChange={p.onOpenChange}><SheetContent/></Sheet>;return <><Sheet open={p.open} onOpenChange={p.onOpenChange}><SheetContent side="right" dir="rtl" className="w-[95vw] overflow-y-auto sm:max-w-3xl"><SheetHeader className="text-right"><div className="flex gap-2"><Badge className={getStatusBadgeClass(r.status)}>{reportStatusLabels[r.status]}</Badge><Badge className={getSeverityBadgeClass(r.severity)}>{reportSeverityLabels[r.severity]}</Badge><Badge variant="outline">{reportEntityTypeLabels[r.entityType]}</Badge></div><SheetTitle className="text-right">{r.title}</SheetTitle><SheetDescription className="text-right">{r.description}</SheetDescription></SheetHeader><div className="space-y-4 py-4"><section className="rounded-lg border p-3 text-xs"><h3 className="mb-2 text-sm font-semibold">أطراف البلاغ</h3><div className="grid gap-2 sm:grid-cols-2"><p>المبلّغ: <b>{r.reporter?.name??toDisplayName(r.reporterName)}</b></p><p>المبلّغ عليه: <b>{r.reportedTarget?.name??'-'}</b></p><p>نوع المبلّغ عليه: <b>{r.reportedTarget?.type==='organization'?'منظمة':r.reportedTarget?.type==='user'?'مستخدم':'-'}</b></p><p>التاريخ: <b>{formatUtcDateTime(r.createdAt)}</b></p><p>المكلّف: <b>{toDisplayName(r.assignee)}</b></p></div></section><section className="rounded-lg border p-3"><h3 className="mb-2 text-sm font-semibold">المحتوى المبلّغ عنه</h3><Entity r={r}/></section><section className="rounded-lg border p-3"><h3 className="mb-2 text-sm font-semibold">سبب وتفاصيل البلاغ</h3><p className="text-xs leading-6">{r.description}</p>{r.evidence?<pre className="mt-2 whitespace-pre-wrap rounded bg-muted p-2 text-xs">{JSON.stringify(r.evidence,null,2)}</pre>:null}</section><section className="rounded-lg border p-3"><h3 className="mb-2 text-sm font-semibold">سجل الإجراءات</h3>{(r.timeline??[]).map((e,i)=><div key={e.id??i} className="mb-2 rounded bg-muted/40 p-2 text-xs"><b>{e.label??e.action??e.status??'إجراء'}</b>{e.note?<p>{e.note}</p>:null}{e.at||e.timestamp?<p>{formatUtcDateTime(e.at??e.timestamp!)}</p>:null}</div>)}</section></div><SheetFooter>{r.status==='new'?<Button disabled={p.isClaiming&&p.claimingReportId===r.id} onClick={()=>p.onClaim(r.id)}>{p.isClaiming&&p.claimingReportId===r.id?<Loader2 className="size-4 animate-spin"/>:null}استلام البلاغ</Button>:null}{r.status==='in_progress'?<Button disabled={p.isClosing&&p.closingReportId===r.id} onClick={()=>setClose(true)}>إغلاق البلاغ</Button>:null}</SheetFooter></SheetContent></Sheet><CloseReportDialog open={close} onOpenChange={setClose} reportTitle={r.title} onConfirm={(note)=>p.onCloseReport(r.id,note)}/></>}
