"use client";
import { useQueryDisclosure } from "@/hooks/use-query-modal";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ReviewStatusBadge, TableRowActions } from "@/components/shared";
import { AppIcons } from "@/constant/icons";
import { formatUtcDateOrDash } from "@/lib/date";
import { displayOrDash } from "@/lib/text";
import { RejectPostDialog } from "./reject-post-dialog";
import { postAudienceLabels, postTypeLabels, publisherTypeLabels, type ReviewPostItem } from "./posts-review.types";

type Props = { posts: ReviewPostItem[]; publishingPostId?: string; blockingPostId?: string; onPublish: (postId: string) => void; onBlock: (postId: string, blockReason: string) => void; onOpenDetails: (post: ReviewPostItem) => void };
export function ReviewPostsTable({ posts, publishingPostId, blockingPostId, onPublish, onBlock, onOpenDetails }: Props) {
  const hasNonPending = posts.some((post) => post.status !== "pending");
  return <div className="rounded-md border border-border bg-card shadow-sm"><Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead className="w-12">#</TableHead><TableHead>الحالة</TableHead><TableHead>العنوان</TableHead><TableHead>الناشر</TableHead><TableHead className="hidden md:table-cell">التصنيف</TableHead><TableHead className="hidden lg:table-cell">الجمهور</TableHead><TableHead className="hidden lg:table-cell">النوع</TableHead>{hasNonPending ? <TableHead className="hidden lg:table-cell">راجعه</TableHead> : null}<TableHead>{hasNonPending ? "تاريخ القرار" : "تاريخ الإرسال"}</TableHead><TableHead>إجراءات</TableHead></TableRow></TableHeader><TableBody>{posts.map((post, index) => <Row key={post.id} post={post} orderNumber={index + 1} showReviewedBy={hasNonPending} publishingPostId={publishingPostId} blockingPostId={blockingPostId} onPublish={onPublish} onBlock={onBlock} onOpenDetails={onOpenDetails} />)}</TableBody></Table></div>;
}
function Row({ post, orderNumber, showReviewedBy, publishingPostId, blockingPostId, onPublish, onBlock, onOpenDetails }: { post: ReviewPostItem; orderNumber: number; showReviewedBy: boolean; publishingPostId?: string; blockingPostId?: string; onPublish: (postId: string) => void; onBlock: (postId: string, blockReason: string) => void; onOpenDetails: (post: ReviewPostItem) => void }) {
  const [dialogOpen, setDialogOpen] = useQueryDisclosure(`post-block-${post.id}`); const date = post.status === "published" ? post.publishedAt : post.status === "blocked" ? post.blockedAt : post.submittedAt; const title = post.title ?? "بدون عنوان";
  return <><TableRow><TableCell className="text-sm text-muted-foreground">{orderNumber}</TableCell><TableCell><ReviewStatusBadge status={post.status} /></TableCell><TableCell><div className="flex flex-col gap-0.5"><span className="font-medium">{title}</span><p className="line-clamp-1 text-xs text-muted-foreground">{displayOrDash(post.summary)}</p>{post.status === "blocked" && post.blockReason ? <p className="line-clamp-1 text-xs text-rose-600">سبب الرفض: {post.blockReason}</p> : null}</div></TableCell><TableCell><div><span>{displayOrDash(post.publisher?.name ?? post.organizationName ?? post.authorName)}</span><div className="text-xs text-muted-foreground">{post.publisher ? publisherTypeLabels[post.publisher.type] : "—"}</div></div></TableCell><TableCell className="hidden md:table-cell">{displayOrDash(post.category?.name)}</TableCell><TableCell className="hidden lg:table-cell">{postAudienceLabels[post.audience ?? "general"]}</TableCell><TableCell className="hidden lg:table-cell">{postTypeLabels[post.type]}</TableCell>{showReviewedBy ? <TableCell className="hidden lg:table-cell">{displayOrDash(post.reviewedBy)}</TableCell> : null}<TableCell>{formatUtcDateOrDash(date)}</TableCell><TableCell><TableRowActions loading={publishingPostId === post.id || blockingPostId === post.id} actions={[{ id: "details", label: "عرض التفاصيل", icon: <AppIcons.eye className="size-4" />, onSelect: () => onOpenDetails(post) }, { id: "publish", label: "قبول ونشر", icon: <AppIcons.posts className="size-4" />, onSelect: () => onPublish(post.id), hidden: post.status !== "pending" }, { id: "block", label: "رفض", icon: <AppIcons.reports className="size-4" />, onSelect: () => setDialogOpen(true), hidden: post.status !== "pending", destructive: true, separatorBefore: true }]} /></TableCell></TableRow><RejectPostDialog open={dialogOpen} onOpenChange={setDialogOpen} postTitle={title} onConfirm={(reason) => onBlock(post.id, reason)} /></>;
}
