import type { AdminGroupPerson } from '@/components/pages/groups-management/groups-management.types'
import type { AdminGroupDetail } from './admin.groups.types'

/**
 * TEMPORARY — seed rows for the groups mock. There is no groups API yet (no
 * migrations, routes or controllers in JOD-backend), and the mobile feature
 * that creates these requests is itself mocked. Delete this file the day
 * admin.groups.services.ts starts calling the real endpoints.
 *
 * The seven active groups mirror `mockGroups` in the mobile app so the same
 * group looks the same on both sides.
 */

export const MOCK_REVIEWER = 'فريق الإشراف'

const person = (id: string, name: string, username: string): AdminGroupPerson => ({
  id,
  name,
  username,
})

type GroupSeed = Pick<AdminGroupDetail, 'id' | 'name' | 'category' | 'status' | 'owner'> &
  Partial<AdminGroupDetail>

function makeGroup(seed: GroupSeed): AdminGroupDetail {
  return {
    location: null,
    visibility: 'public',
    membersCount: 0,
    postsThisWeek: 0,
    postsCount: 0,
    imageUrl: null,
    organizationName: null,
    isVerifiedOrganization: false,
    ownerName: seed.owner.name,
    rejectionReason: null,
    suspensionReason: null,
    submittedAt: null,
    reviewedAt: null,
    reviewedBy: null,
    createdAt: null,
    description: '',
    rules: [],
    purpose: '',
    proposedAdmins: [],
    ...seed,
  }
}

const pendingGroups: AdminGroupDetail[] = [
  makeGroup({
    id: 'grp-101',
    name: 'متطوعو حماة',
    category: 'تطوع',
    location: 'حماة',
    status: 'pending',
    owner: person('usr-001', 'أحمد الحسين', 'ahmad.h'),
    proposedAdmins: [person('usr-006', 'رزان الحسن', 'razan')],
    description: 'تنسيق الحملات التطوعية الميدانية في حماة وريفها ونشر الفرص الأسبوعية.',
    purpose: 'ما في مجموعة تغطي حماة حالياً، وفي فريق تطوعي فعّال بحاجة لمكان ينسّق فيه.',
    rules: [
      'احترم جميع الأعضاء وتجنّب أي إساءة أو تنمّر.',
      'لا تنشر طلبات تبرع مالي شخصية داخل المجموعة.',
      'التزم بمواعيد الحملات التي تسجّل فيها.',
    ],
    submittedAt: '2026-08-28T09:15:00Z',
  }),
  makeGroup({
    id: 'grp-102',
    name: 'دروس تقوية مجانية',
    category: 'تعليم',
    location: 'دمشق',
    status: 'pending',
    owner: person('usr-002', 'لجين حياني', 'lujain'),
    proposedAdmins: [
      person('usr-005', 'عبد الجواد الحاج', 'abdaljawad'),
      person('usr-008', 'ميس أكتع', 'mays'),
    ],
    description: 'ربط طلاب الشهادتين بمدرّسين متطوعين لتقديم دروس تقوية مجانية.',
    purpose: 'التنسيق حالياً عبر مجموعات واتساب مبعثرة وبتضيع المتابعة.',
    rules: [
      'الدروس مجانية بالكامل — ممنوع طلب أي أجر.',
      'لا تشارك بيانات تواصل الطلاب القاصرين.',
      'المدرّس المتطوع يلتزم بالموعد أو يعتذر مسبقاً.',
    ],
    submittedAt: '2026-08-27T14:02:00Z',
  }),
  makeGroup({
    id: 'grp-103',
    name: 'سلة رمضان',
    category: 'إغاثة',
    location: 'درعا',
    visibility: 'private',
    status: 'pending',
    owner: person('usr-003', 'مصطفى فارس', 'mustafa.f'),
    organizationName: 'مؤسسة عطاء',
    isVerifiedOrganization: true,
    description: 'تنظيم توزيع السلال الغذائية في رمضان وتوثيق الحالات المستفيدة.',
    purpose: 'المجموعة خاصة لأن فيها بيانات أسر مستفيدة ولازم تبقى محصورة بالفريق.',
    rules: [
      'التوزيع يتم عبر المؤسسة حصراً — لا تنسيق فردي.',
      'لا تنشر صور المستفيدين أو أسماءهم.',
      'بلّغ عن أي طلب تبرع مشبوه فوراً.',
    ],
    submittedAt: '2026-08-26T08:40:00Z',
  }),
  makeGroup({
    id: 'grp-104',
    name: 'دعم مرضى الكلى',
    category: 'صحة',
    location: 'حلب',
    visibility: 'private',
    status: 'pending',
    owner: person('usr-004', 'شهد بوادقجي', 'shahd.b'),
    proposedAdmins: [person('usr-007', 'باسل العساف', 'basel.a')],
    description: 'متابعة مواعيد الغسيل الكلوي وتأمين الأدوية للحالات المحتاجة.',
    purpose: 'الحالات حسّاسة وبحاجة متابعة دورية ومكان مغلق للتنسيق.',
    rules: [
      'حافظ على سرّية أي معلومة صحية تطّلع عليها.',
      'لا تقدّم استشارات طبية إن لم تكن مختصاً.',
      'ممنوع نشر أسماء المرضى أو صورهم.',
    ],
    submittedAt: '2026-08-25T17:20:00Z',
  }),
  makeGroup({
    id: 'grp-105',
    name: 'حرفيون بلا حدود',
    category: 'تمكين اقتصادي',
    location: 'حمص',
    status: 'pending',
    owner: person('usr-005', 'عبد الجواد الحاج', 'abdaljawad'),
    description: 'تسويق منتجات الحرفيين وتبادل الخبرات وفرص التدريب المهني.',
    purpose: 'في حرفيين كتير بحمص ما عندهم أي منفذ تسويقي رقمي.',
    rules: [
      'المنشورات مخصّصة للمنتجات الحرفية فقط.',
      'اذكر السعر بوضوح ولا تبالغ في الوصف.',
      'ممنوع التسويق لجهات تجارية كبيرة.',
    ],
    submittedAt: '2026-08-24T11:05:00Z',
  }),
  makeGroup({
    id: 'grp-106',
    name: 'كفالة طلاب الثانوية',
    category: 'كفالات',
    location: 'اللاذقية',
    visibility: 'private',
    status: 'pending',
    owner: person('usr-006', 'رزان الحسن', 'razan'),
    proposedAdmins: [person('usr-010', 'فيحاء الخليفة', 'fayhaa')],
    description: 'ربط الكافلين بطلاب الثانوية المتعثرين مادياً ومتابعة استمرارهم بالدراسة.',
    purpose: 'الكفالة التزام طويل ولازم يكون في متابعة موثّقة بعيداً عن الجمهور.',
    rules: [
      'بيانات الطلاب وأسرهم سرّية ولا تُنشر خارج المجموعة.',
      'التواصل مع الأسر يتم عبر المشرفين فقط.',
      'لا تسجّل ككافل إن لم تكن قادراً على الاستمرار سنة كاملة.',
    ],
    submittedAt: '2026-08-23T19:48:00Z',
  }),
  makeGroup({
    id: 'grp-107',
    name: 'وظائف تقنية للخريجين',
    category: 'توظيف',
    location: 'دمشق',
    status: 'pending',
    owner: person('usr-007', 'باسل العساف', 'basel.a'),
    description: 'إعلانات وظائف وتدريبات في مجال البرمجة والتصميم للخريجين الجدد.',
    purpose: 'مجموعة فرص العمل العامة واسعة، وبدنا وحدة مختصة بالتقنية.',
    rules: [
      'انشر إعلانات وظائف حقيقية فقط مع تفاصيل واضحة.',
      'ممنوع طلب أي رسوم من المتقدمين.',
      'لا تنشر بيانات التواصل الشخصية للآخرين.',
    ],
    submittedAt: '2026-08-22T07:31:00Z',
  }),
  makeGroup({
    id: 'grp-108',
    name: 'إغاثة السويداء',
    category: 'إغاثة',
    location: 'السويداء',
    status: 'pending',
    owner: person('usr-008', 'ميس أكتع', 'mays'),
    proposedAdmins: [person('usr-009', 'نوّار أبو عمّاش', 'nawwar')],
    description: 'تنسيق الاستجابة السريعة للحالات الطارئة في السويداء والقرى المحيطة.',
    purpose: 'الاستجابة حالياً بطيئة لأن ما في قناة تنسيق موحّدة بالمحافظة.',
    rules: [
      'تحقّق من الحالة قبل نشرها.',
      'لا تكرّر نشر نفس الحالة أكثر من مرة.',
      'التنسيق مع الجهات الرسمية إلزامي بالحالات الطارئة.',
    ],
    submittedAt: '2026-08-21T13:12:00Z',
  }),
  makeGroup({
    id: 'grp-109',
    name: 'أمهات وأطفال',
    category: 'صحة',
    location: 'طرطوس',
    visibility: 'private',
    status: 'pending',
    owner: person('usr-009', 'نوّار أبو عمّاش', 'nawwar'),
    description: 'توعية صحية للأمهات الجدد ومتابعة لقاحات الأطفال ومواعيد العيادات.',
    purpose: 'محتوى المجموعة شخصي وحسّاس، والأمهات بيفضّلوا مساحة مغلقة.',
    rules: [
      'المحتوى توعوي فقط ولا يغني عن استشارة الطبيب.',
      'ممنوع الترويج لأي منتج أو حليب صناعي.',
      'احترم خصوصية أي حالة تُطرح داخل المجموعة.',
    ],
    submittedAt: '2026-08-20T10:55:00Z',
  }),
  makeGroup({
    id: 'grp-110',
    name: 'مكتبة مستعملة',
    category: 'تعليم',
    location: 'دير الزور',
    status: 'pending',
    owner: person('usr-010', 'فيحاء الخليفة', 'fayhaa'),
    description: 'تبادل وإهداء الكتب المدرسية والجامعية المستعملة بدل رميها.',
    purpose: 'كل سنة بتنرمي كتب كتير وفي طلاب ما بيقدروا يشتروا جداد.',
    rules: [
      'الكتب للإهداء أو التبادل — ممنوع البيع.',
      'اذكر حالة الكتاب بصدق.',
      'التسليم يتم بمكان عام وآمن.',
    ],
    submittedAt: '2026-08-19T16:07:00Z',
  }),
]

const activeGroups: AdminGroupDetail[] = [
  makeGroup({
    id: 'grp-001',
    name: 'متطوعو دمشق',
    category: 'تطوع',
    location: 'دمشق',
    status: 'active',
    owner: person('usr-001', 'أحمد الحسين', 'ahmad.h'),
    proposedAdmins: [person('usr-002', 'لجين حياني', 'lujain')],
    organizationName: 'جمعية البركة',
    isVerifiedOrganization: true,
    membersCount: 2431,
    postsThisWeek: 18,
    postsCount: 642,
    description: 'تنسيق حملات التطوع الميداني داخل دمشق وريفها، ومشاركة الفرص الأسبوعية.',
    purpose: 'الجمعية بحاجة لقناة تنسيق مباشرة مع المتطوعين.',
    rules: [
      'احترم جميع الأعضاء وتجنّب أي إساءة أو تنمّر.',
      'لا تنشر طلبات تبرع مالي شخصية داخل المجموعة.',
      'التزم بمواعيد الحملات التي تسجّل فيها.',
    ],
    submittedAt: '2024-03-02T08:00:00Z',
    reviewedAt: '2024-03-04T09:30:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2024-03-04T09:30:00Z',
  }),
  makeGroup({
    id: 'grp-002',
    name: 'دعم طلاب الجامعات',
    category: 'تعليم',
    location: 'حلب',
    status: 'active',
    owner: person('usr-002', 'لجين حياني', 'lujain'),
    proposedAdmins: [person('usr-006', 'رزان الحسن', 'razan')],
    membersCount: 1876,
    postsThisWeek: 24,
    postsCount: 908,
    description: 'مساعدات دراسية، كتب مستعملة، وفرص سكن للطلاب الجامعيين.',
    purpose: 'تجميع كل ما يخص الطالب الجامعي بمكان واحد.',
    rules: [
      'المحتوى المسموح: مواد دراسية وفرص سكن ودعم طلابي فقط.',
      'لا تشارك بيانات طلاب آخرين دون إذنهم.',
      'ممنوع بيع الكتب بأسعار مضاعفة.',
    ],
    submittedAt: '2023-09-10T08:00:00Z',
    reviewedAt: '2023-09-12T12:00:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2023-09-12T12:00:00Z',
  }),
  makeGroup({
    id: 'grp-003',
    name: 'إغاثة الشتاء',
    category: 'إغاثة',
    location: 'إدلب',
    status: 'active',
    owner: person('usr-003', 'مصطفى فارس', 'mustafa.f'),
    organizationName: 'مؤسسة عطاء',
    isVerifiedOrganization: true,
    membersCount: 5209,
    postsThisWeek: 41,
    postsCount: 1533,
    description: 'توزيع البطانيات والمدافئ والملابس الشتوية على الأسر الأكثر حاجة.',
    purpose: 'حملة سنوية بحاجة لتنسيق دائم.',
    rules: [
      'التوزيع يتم عبر المنظمة حصراً — لا تنسيق فردي.',
      'لا تنشر صور المستفيدين أو أسماءهم.',
      'بلّغ عن أي طلب تبرع مشبوه فوراً.',
    ],
    submittedAt: '2022-11-05T08:00:00Z',
    reviewedAt: '2022-11-07T10:15:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2022-11-07T10:15:00Z',
  }),
  makeGroup({
    id: 'grp-004',
    name: 'الأسر المنتجة',
    category: 'تمكين اقتصادي',
    location: 'اللاذقية',
    status: 'active',
    owner: person('usr-010', 'فيحاء الخليفة', 'fayhaa'),
    membersCount: 934,
    postsThisWeek: 7,
    postsCount: 289,
    description: 'تسويق منتجات الأسر المنتجة ودعم المشاريع الصغيرة المنزلية.',
    purpose: 'فتح منفذ تسويقي للأسر المنتجة.',
    rules: [
      'المنشورات مخصّصة للمنتجات المنزلية فقط.',
      'اذكر السعر بوضوح ولا تبالغ في الوصف.',
      'ممنوع التسويق لجهات تجارية كبيرة.',
    ],
    submittedAt: '2024-06-14T08:00:00Z',
    reviewedAt: '2024-06-16T11:40:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2024-06-16T11:40:00Z',
  }),
  makeGroup({
    id: 'grp-005',
    name: 'رعاية صحية مجانية',
    category: 'صحة',
    location: 'حمص',
    visibility: 'private',
    status: 'active',
    owner: person('usr-005', 'عبد الجواد الحاج', 'abdaljawad'),
    organizationName: 'الهلال الطبي',
    isVerifiedOrganization: true,
    membersCount: 1425,
    postsThisWeek: 12,
    postsCount: 476,
    description: 'مواعيد العيادات المجانية والحملات الطبية والتبرع بالأدوية.',
    purpose: 'تنسيق المواعيد الطبية بشكل مغلق حفاظاً على خصوصية المرضى.',
    rules: [
      'حافظ على سرّية أي معلومة صحية تطّلع عليها.',
      'لا تقدّم استشارات طبية إن لم تكن مختصاً.',
      'ممنوع نشر أسماء المرضى أو صورهم.',
    ],
    submittedAt: '2023-01-18T08:00:00Z',
    reviewedAt: '2023-01-20T09:00:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2023-01-20T09:00:00Z',
  }),
  makeGroup({
    id: 'grp-006',
    name: 'كفالة الأيتام',
    category: 'كفالات',
    location: 'دمشق',
    visibility: 'private',
    status: 'active',
    owner: person('usr-001', 'أحمد الحسين', 'ahmad.h'),
    organizationName: 'جمعية البركة',
    isVerifiedOrganization: true,
    membersCount: 3102,
    postsThisWeek: 9,
    postsCount: 731,
    description: 'ربط الكافلين بالأسر المحتاجة ومتابعة حالات الأطفال الأيتام.',
    purpose: 'متابعة الكفالات بشكل موثّق ومغلق.',
    rules: [
      'بيانات الأطفال والأسر سرّية ولا تُنشر خارج المجموعة.',
      'التواصل مع الأسر يتم عبر المشرفين فقط.',
      'الكفالة التزام طويل — لا تسجّل إن لم تكن قادراً على الاستمرار.',
    ],
    submittedAt: '2021-05-03T08:00:00Z',
    reviewedAt: '2021-05-06T14:25:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2021-05-06T14:25:00Z',
  }),
  makeGroup({
    id: 'grp-007',
    name: 'فرص عمل للشباب',
    category: 'توظيف',
    location: 'طرطوس',
    status: 'active',
    owner: person('usr-007', 'باسل العساف', 'basel.a'),
    membersCount: 612,
    postsThisWeek: 15,
    postsCount: 344,
    description: 'إعلانات وظائف وتدريبات مهنية موجهة للخريجين الجدد.',
    purpose: 'تجميع فرص العمل الموثوقة بمكان واحد.',
    rules: [
      'انشر إعلانات وظائف حقيقية فقط مع تفاصيل واضحة.',
      'ممنوع طلب أي رسوم من المتقدمين.',
      'لا تنشر بيانات التواصل الشخصية للآخرين.',
    ],
    submittedAt: '2025-02-11T08:00:00Z',
    reviewedAt: '2025-02-13T10:05:00Z',
    reviewedBy: MOCK_REVIEWER,
    createdAt: '2025-02-13T10:05:00Z',
  }),
]

const moderatedGroups: AdminGroupDetail[] = [
  makeGroup({
    id: 'grp-301',
    name: 'سوق دمشق',
    category: 'أخرى',
    location: 'دمشق',
    status: 'rejected',
    owner: person('usr-004', 'شهد بوادقجي', 'shahd.b'),
    description: 'بيع وشراء كل أنواع البضائع.',
    purpose: 'مجموعة تجارية عامة.',
    rules: ['البيع والشراء مسموح.'],
    submittedAt: '2026-07-14T08:00:00Z',
    reviewedAt: '2026-07-15T10:20:00Z',
    reviewedBy: MOCK_REVIEWER,
    rejectionReason: 'الغرض تجاري بحت ولا يتوافق مع طبيعة المنصة الخيرية.',
  }),
  makeGroup({
    id: 'grp-302',
    name: 'مجموعة بدون وصف',
    category: 'أخرى',
    location: 'حمص',
    status: 'rejected',
    owner: person('usr-009', 'نوّار أبو عمّاش', 'nawwar'),
    description: 'مجموعة عامة.',
    purpose: 'للتواصل.',
    rules: [],
    submittedAt: '2026-06-30T08:00:00Z',
    reviewedAt: '2026-07-01T09:10:00Z',
    reviewedBy: MOCK_REVIEWER,
    rejectionReason: 'الوصف والقوانين غير كافية لتحديد هدف المجموعة. يمكن إعادة الإرسال بعد التوضيح.',
  }),
  makeGroup({
    id: 'grp-303',
    name: 'تبرعات نقدية مباشرة',
    category: 'إغاثة',
    location: 'إدلب',
    status: 'rejected',
    owner: person('usr-006', 'رزان الحسن', 'razan'),
    description: 'جمع التبرعات النقدية وتحويلها مباشرة للأسر.',
    purpose: 'تسريع وصول المبالغ للمحتاجين.',
    rules: ['التحويل عبر المشرف فقط.'],
    submittedAt: '2026-06-12T08:00:00Z',
    reviewedAt: '2026-06-13T13:45:00Z',
    reviewedBy: MOCK_REVIEWER,
    rejectionReason: 'المنصة لا تتعامل مع التحويلات المالية، وجمع التبرعات النقدية مخالف للشروط.',
  }),
]

export const seededAdminGroups: AdminGroupDetail[] = [
  ...pendingGroups,
  ...activeGroups,
  ...moderatedGroups,
]
