import {
  Archive,
  Award,
  BadgeCheck,
  Bell,
  BookOpenText,
  Eye,
  ChartColumnBig,
  ChevronLeft,
  ChevronRight,
  FileCheck2,
  Mail,
  MailOpen,
  HandHeart,
  History,
  LayoutDashboard,
  LogOut,
  Megaphone,
  Menu,
  Monitor,
  MoonStar,
  Pin,
  PanelRightClose,
  PanelRightOpen,
  RotateCw,
  Search,
  Send,
  Settings,
  ShieldAlert,
  Sun,
  Target,
  UserCircle2,
  UserCog,
  Users,
  Building2,
  UserRoundPen,
  UserRoundX,
  UserPlus,
  UserX,
  UserLock,
  Trash,
  ShieldCheck,
  ShieldOff,
  PencilLine,
  BadgeMinus,
  type LucideIcon,
} from "lucide-react";

export const AppIcons = {
  BadgeMinus,
  PencilLine,
  ShieldOff,
  ShieldCheck,
  menu: Menu,
  collapse: PanelRightClose,
  expand: PanelRightOpen,
  pin: Pin,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  dashboard: LayoutDashboard,
  posts: FileCheck2,
  campaigns: Megaphone,
  reports: ShieldAlert,
  users: Users,
  organizations: Building2,
  verification: BadgeCheck,
  notifications: Bell,
  send: Send,
  archive: Archive,
  eye: Eye,
  mail: Mail,
  mailOpen: MailOpen,
  rotateCw: RotateCw,
  rewards: Award,
  content: BookOpenText,
  analytics: ChartColumnBig,
  auditLog: History,
  settings: Settings,
  profile: UserCircle2,
  donors: HandHeart,
  staff: UserCog,
  goal: Target,
  logout: LogOut,
  themeLight: Sun,
  themeDark: MoonStar,
  themeSystem: Monitor,
  UserRoundPen,
  UserRoundX,
  UserPlus,
  UserX,
  UserLock,
  Trash,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof AppIcons;
export type AppIcon = (typeof AppIcons)[AppIconName];
