'use client'
import * as React from 'react'
import Link from 'next/link'
import { DetailsLoadingSkeleton } from '@/components/shared'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useAdminUser, useAdminUserDonations, useAdminUserPersonalization, useAdminUserPosts } from '@/features/admin/users/admin.users.query'
import { formatUtcDateTimeOrDash } from '@/lib/date'
import { routePaths } from '@/constant/routes'

const intentLabels={giver:'تقديم المساعدة',receiver:'طلب المساعدة',both:'كلاهما'} as const
const availabilityLabels:Record<string,string>={available:'متاح',busy:'مشغول',weekends:'عطلة نهاية الأسبوع',evenings:'المساء',remote_only:'عن بعد فقط'}

export function UserDetailsPage({userId}:{userId:string}){
  const [postsPage,setPostsPage]=React.useState(1); const [postsPerPage,setPostsPerPage]=React.useState(20)
  const [donationsPage,setDonationsPage]=React.useState(1); const [donationsPerPage,setDonationsPerPage]=React.useState(20)
  const user=useAdminUser(userId); const posts=useAdminUserPosts(userId,{page:postsPage,perPage:postsPerPage}); const donations=useAdminUserDonations(userId,{page:donationsPage,perPage:donationsPerPage}); const personalization=useAdminUserPersonalization(userId)
  const u=user.data?.data; const p=personalization.data?.data
  return <section className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">تفاصيل المستخدم</h2><p className="text-sm text-muted-foreground">بيانات الحساب والنشاط والتفضيلات الشخصية.</p></div><Button asChild variant="outline"><Link href={routePaths.adminScope.users}>العودة للمستخدمين</Link></Button></div>
    {user.isLoading?<DetailsLoadingSkeleton />:u?<div className="grid gap-3 rounded-lg border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="الاسم" value={u.name}/><Info label="البريد" value={u.email}/><Info label="الهاتف" value={u.phone||'-'}/><div><p className="text-xs text-muted-foreground">الحالة</p><Badge variant="outline">{u.status}</Badge></div></div>:null}
    <Tabs defaultValue="posts" dir="rtl"><TabsList><TabsTrigger value="posts">المنشورات</TabsTrigger><TabsTrigger value="donations">التبرعات</TabsTrigger><TabsTrigger value="personalization">التفضيلات والتخصيص</TabsTrigger></TabsList>
      <TabsContent value="posts" className="space-y-3"><div className="overflow-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>العنوان</TableHead><TableHead>النوع</TableHead><TableHead>الحالة</TableHead><TableHead>المنظمة</TableHead><TableHead>تاريخ الإنشاء</TableHead><TableHead>التفاعل</TableHead></TableRow></TableHeader><TableBody>{posts.isLoading?<TableSkeleton cols={6}/>:posts.data?.data.length?posts.data.data.map(item=><TableRow key={item.id}><TableCell className="max-w-72"><p className="font-medium">{item.title||'-'}</p><p className="truncate text-xs text-muted-foreground">{item.summary||item.description||''}</p></TableCell><TableCell>{item.type}</TableCell><TableCell><Badge variant="outline">{item.status}</Badge></TableCell><TableCell>{item.organizationName||'-'}</TableCell><TableCell>{formatUtcDateTimeOrDash(item.createdAt)}</TableCell><TableCell className="text-xs">مشاهدات {item.viewsCount} / تفاعلات {item.reactionsCount}</TableCell></TableRow>):<EmptyRow cols={6} text="لا توجد منشورات."/>}</TableBody></Table></div><Pager page={postsPage} perPage={postsPerPage} lastPage={posts.data?.meta.lastPage??1} total={posts.data?.meta.total??0} setPage={setPostsPage} setPerPage={setPostsPerPage}/></TabsContent>
      <TabsContent value="donations" className="space-y-3"><div className="overflow-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>الحملة</TableHead><TableHead>المنظمة</TableHead><TableHead>المبلغ</TableHead><TableHead>طريقة الدفع</TableHead><TableHead>المدينة</TableHead><TableHead>التاريخ</TableHead></TableRow></TableHeader><TableBody>{donations.isLoading?<TableSkeleton cols={6}/>:donations.data?.data.length?donations.data.data.map(item=><TableRow key={item.id}><TableCell>{item.campaignTitle||'-'}</TableCell><TableCell>{item.organizationName||'-'}</TableCell><TableCell>{item.amount!=null?item.amount.toLocaleString('ar-SY'):item.amountOrType}</TableCell><TableCell>{item.paymentMethod||'-'}</TableCell><TableCell>{item.city||'-'}</TableCell><TableCell>{formatUtcDateTimeOrDash(item.donatedAt||item.createdAt)}</TableCell></TableRow>):<EmptyRow cols={6} text="لا توجد تبرعات."/>}</TableBody></Table></div><Pager page={donationsPage} perPage={donationsPerPage} lastPage={donations.data?.meta.lastPage??1} total={donations.data?.meta.total??0} setPage={setDonationsPage} setPerPage={setDonationsPerPage}/></TabsContent>
      <TabsContent value="personalization" className="space-y-4">{personalization.isLoading?<PersonalizationSkeleton/>:personalization.isError?<div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">تعذر تحميل بيانات التخصيص. <button className="underline" onClick={()=>personalization.refetch()}>إعادة المحاولة</button></div>:p?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="هدف الاستخدام" value={p.intent?intentLabels[p.intent]:'-'}/><Info label="الموقع" value={[p.preferredCity,p.preferredGovernorate].filter(Boolean).join('، ')||'-'}/><Info label="التوفر" value={p.availabilityStatus?availabilityLabels[p.availabilityStatus]??p.availabilityStatus:'-'}/><Info label="المساعدة عن بعد" value={p.remoteHelpEnabled?'مفعل':'غير مفعل'}/></div><Panel title="الاهتمامات الصريحة"><div className="flex flex-wrap gap-2">{p.interests.filter(x=>x.selectedByUser).map(x=><Badge key={x.category.id} variant="outline">{x.category.name}</Badge>)}{!p.interests.some(x=>x.selectedByUser)?<Muted>لا توجد اهتمامات محددة.</Muted>:null}</div></Panel><Panel title="الاهتمامات المكتسبة من السلوك"><div className="space-y-2">{[...p.interests].filter(x=>x.behavioralWeight>0).sort((a,b)=>b.behavioralWeight-a.behavioralWeight).map(x=><div key={x.category.id} className="flex justify-between rounded-md bg-muted/40 px-3 py-2 text-sm"><span>{x.category.name}</span><strong>{x.behavioralWeight}</strong></div>)}{!p.interests.some(x=>x.behavioralWeight>0)?<Muted>لا توجد بيانات سلوكية بعد.</Muted>:null}</div></Panel><Panel title="طرق المساعدة"><div className="flex flex-wrap gap-2">{p.capabilities.map(x=><Badge key={x.id} variant="secondary">{x.name}</Badge>)}{!p.capabilities.length?<Muted>لم يحدد المستخدم طرق مساعدة.</Muted>:null}</div></Panel><Panel title="ملخص التفاعل مع التوصيات"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="مهتم" value={p.feedback.interested}/><Metric label="غير مهتم" value={p.feedback.notInterested}/><Metric label="منشورات مخفية" value={p.feedback.hiddenPosts}/><Metric label="ناشرون مخفيون" value={p.feedback.hiddenPublishers}/></div></Panel></>:null}</TabsContent>
    </Tabs>
  </section>
}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-lg border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border bg-card p-4"><h3 className="mb-3 text-sm font-semibold">{title}</h3>{children}</div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-lg bg-muted/40 p-3 text-center"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>}
function Muted({children}:{children:React.ReactNode}){return <p className="text-sm text-muted-foreground">{children}</p>}
function PersonalizationSkeleton(){return <div className="space-y-4">{[0,1,2].map(i=><div key={i} className="h-28 animate-pulse rounded-lg border bg-muted/50"/>)}</div>}
function TableSkeleton({cols}:{cols:number}){return <>{Array.from({length:4}).map((_,i)=><TableRow key={i}><TableCell colSpan={cols}><div className="h-5 animate-pulse rounded bg-muted"/></TableCell></TableRow>)}</>}
function EmptyRow({cols,text}:{cols:number;text:string}){return <TableRow><TableCell colSpan={cols} className="py-10 text-center text-muted-foreground">{text}</TableCell></TableRow>}
function Pager({page,perPage,lastPage,total,setPage,setPerPage}:{page:number;perPage:number;lastPage:number;total:number;setPage:(n:number)=>void;setPerPage:(n:number)=>void}){return <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">الصفحة {page} من {lastPage} - الإجمالي {total}</p><div className="flex items-center gap-2"><select className="h-9 rounded-md border bg-background px-2 text-sm" value={perPage} onChange={(e)=>{setPerPage(Number(e.target.value));setPage(1)}}>{[10,20,50,100].map(n=><option key={n} value={n}>{n}</option>)}</select><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(Math.max(1,page-1))}>السابق</Button><Button size="sm" variant="outline" disabled={page>=lastPage} onClick={()=>setPage(page+1)}>التالي</Button></div></div>}
